// This file is automatically generated by FireVibe. Do not edit it directly.
//
// This app's AI access: an OpenAI-compatible provider for the Vercel AI SDK,
// routed through the FireVibe AI gateway. Use it ONLY inside server routes
// and server functions (the API key is server-runtime only; the build
// refuses client imports of this module).
//
// RUN LIFECYCLE — the gateway meters usage per run and ASSIGNS the run id:
// create ONE provider per incoming request; its fetch echoes the current run
// id to the gateway and captures the assigned one from the response. To
// continue a run across requests, read the id from the incoming request and
// pass it back in; to let the browser carry it, forward the gateway headers
// onto your response:
//
//   import { convertToModelMessages, streamText } from 'ai'
//   import {
//     aiResponseHeaders, createAiProvider, getAiRunId,
//   } from '@/server/ai'
//
//   const gateway = createAiProvider(getAiRunId(request))
//   const result = streamText({
//     model: gateway('MODEL_ID'),
//     messages: await convertToModelMessages(messages),
//   })
//   // when building the response:
//   //   headers: aiResponseHeaders({ 'X-FireVibe-AIG-Run-ID':
//   //     (await gateway.waitForRunId()) ?? '' })
//
// AI is configured by FireVibe when enabled for this app; until then
// provider creation throws with a clear message (import alone is always
// safe).
import '@tanstack/react-start/server-only'

import { createOpenAICompatible } from '@ai-sdk/openai-compatible'

const RUN_ID_HEADER = 'X-FireVibe-AIG-Run-ID'
const AIG_HEADER_PREFIX = 'x-firevibe-aig-'
const DEFAULT_GATEWAY_URL = 'https://ai.firevibe.dev/v1'

function apiKey(): string {
  const key = process.env['FIREVIBE_API_KEY']
  if (!key) {
    throw new Error(
      'AI is not configured for this app yet. FireVibe sets ' +
        'FIREVIBE_API_KEY when AI is enabled.',
    )
  }
  return key
}

function gatewayUrl(): string {
  return process.env['FIREVIBE_AI_URL'] ?? DEFAULT_GATEWAY_URL
}

/**
 * A fetch bound to one run: echoes the known run id to the gateway and
 * captures the assigned one from the first response.
 */
export function createAiRunFetch(initialRunId?: string) {
  let runId = initialRunId?.trim() || undefined
  let resolveRunId: (value: string | undefined) => void = () => {}
  let runIdResolved = false
  const runIdReady = new Promise<string | undefined>((resolve) => {
    resolveRunId = resolve
  })

  const publishRunId = (value?: string) => {
    const nextRunId = value?.trim() || undefined
    if (!runId && nextRunId) {
      runId = nextRunId
    }
    if (!runIdResolved) {
      runIdResolved = true
      resolveRunId(runId)
    }
  }
  if (runId) publishRunId(runId)

  return {
    fetch: async (input: RequestInfo | URL, init?: RequestInit) => {
      const headers = new Headers(init?.headers)
      if (runId && !headers.has(RUN_ID_HEADER)) {
        headers.set(RUN_ID_HEADER, runId)
      }
      try {
        const response = await fetch(input, { ...init, headers })
        publishRunId(response.headers.get(RUN_ID_HEADER) ?? undefined)
        return response
      } catch (error) {
        publishRunId(undefined)
        throw error
      }
    },
    getRunId: () => runId,
    waitForRunId: () => (runId ? Promise.resolve(runId) : runIdReady),
  }
}

/**
 * One provider per incoming request: `gateway('MODEL_ID')` yields a model
 * for the AI SDK; `getRunId`/`waitForRunId` expose the gateway-assigned run
 * id for continuation and response headers.
 */
export function createAiProvider(initialRunId?: string) {
  const runFetch = createAiRunFetch(initialRunId)

  const provider = createOpenAICompatible({
    name: 'firevibe',
    baseURL: gatewayUrl(),
    headers: {
      'FireVibe-API-Key': apiKey(),
      'X-FireVibe-AIG-SDK': 'vercel-ai-sdk',
    },
    fetch: runFetch.fetch,
  })

  return Object.assign(provider, {
    getRunId: runFetch.getRunId,
    waitForRunId: runFetch.waitForRunId,
  })
}

/** The run id carried by an incoming request, if the caller is continuing one. */
export function getAiRunId(request: Request): string | undefined {
  return request.headers.get(RUN_ID_HEADER)?.trim() || undefined
}

/**
 * Response headers that forward the gateway's X-FireVibe-AIG-* headers to
 * the browser (with CORS exposure), so the client can carry the run id into
 * its next request.
 */
export function aiResponseHeaders(
  gatewayHeaders: HeadersInit | undefined,
  init?: HeadersInit,
): Headers {
  const headers = new Headers(init)
  const exposedHeaders = new Set(
    (headers.get('Access-Control-Expose-Headers') ?? '')
      .split(',')
      .map((header) => header.trim())
      .filter(Boolean),
  )

  new Headers(gatewayHeaders).forEach((value, name) => {
    if (name.toLowerCase().startsWith(AIG_HEADER_PREFIX)) {
      headers.set(name, value)
      exposedHeaders.add(name)
    }
  })

  headers.forEach((_, name) => {
    if (name.toLowerCase().startsWith(AIG_HEADER_PREFIX)) {
      exposedHeaders.add(name)
    }
  })

  if (exposedHeaders.size > 0) {
    headers.set(
      'Access-Control-Expose-Headers',
      Array.from(exposedHeaders).join(', '),
    )
  }

  return headers
}
