// This file is automatically generated by FireVibe. Do not edit it directly.
//
// The app's authentication core: Better Auth in minimal mode (adapter-only)
// over the same db.ts the data layer uses — users and sessions live in this
// app's OWN Postgres, owned by the app, no external auth service. Server
// code gates data access with requireSession from '@/server/session' (never
// import this module from client code — the build will refuse it). The auth
// HTTP endpoints are mounted at /api/auth/* by src/routes/api/auth/$.ts, and
// browser code talks to them through '@/lib/auth-client'.
//
// Email verification is OFF by default (the library default — owner ruling
// 2026-08-14: an opt-in knob, never a forced wall) and becomes available as
// a configure_auth setting once the FireVibe platform email sender exists.
// Social sign-in (FireVibe broker) is added by the platform when enabled —
// do not hand-wire OAuth providers here.
import '@tanstack/react-start/server-only'

import { drizzleAdapter } from 'better-auth/adapters/drizzle'
import { betterAuth } from 'better-auth/minimal'
import { tanstackStartCookies } from 'better-auth/tanstack-start'

import { db } from './db'
import * as schema from './schema'

// BETTER_AUTH_SECRET and BETTER_AUTH_URL come from the environment (dev: the
// project .env written by FireVibe; production: Worker secrets injected at
// deploy) — Better Auth reads both itself and refuses to run in production
// without a secret. BETTER_AUTH_TRUSTED_ORIGINS (comma-separated, also
// FireVibe-managed) extends the origin check beyond the baseURL: the
// sandbox's own localhost (agent verification) and the development preview
// surface. Never hand-edit the .env — FireVibe rewrites it every session.
const trustedOrigins = (process.env['BETTER_AUTH_TRUSTED_ORIGINS'] ?? '')
  .split(',')
  .map((origin) => origin.trim())
  .filter(Boolean)

// Auth policy knobs (FIREVIBE_AUTH_*, also FireVibe-managed): present only
// when the user explicitly changed a setting through the platform — absent
// means the library default (open sign-up, 8-char minimum, 7-day
// sessions). Managed with the configure_auth platform tool, never by
// editing this file or the .env.
const minPasswordLength =
  Number(process.env['FIREVIBE_AUTH_MIN_PASSWORD_LENGTH'] ?? '') || undefined
const sessionExpiresIn =
  Number(process.env['FIREVIBE_AUTH_SESSION_EXPIRES_IN'] ?? '') || undefined
const disableSignUp = process.env['FIREVIBE_AUTH_DISABLE_SIGNUP'] === 'true'

export const auth = betterAuth({
  database: drizzleAdapter(db, { provider: 'pg', schema }),
  emailAndPassword: {
    enabled: true,
    ...(disableSignUp ? { disableSignUp: true } : {}),
    ...(minPasswordLength ? { minPasswordLength } : {}),
  },
  ...(sessionExpiresIn ? { session: { expiresIn: sessionExpiresIn } } : {}),
  ...(trustedOrigins.length > 0 ? { trustedOrigins } : {}),
  // Session cookies must survive the FireVibe workspace, which embeds this
  // app's preview in a cross-site iframe (app.firevibe.ai framing a
  // firevibe.dev host). The library default, SameSite=Lax, is never sent
  // inside such a frame, so a sign-in there could not keep its session
  // while the same app worked in its own tab (fixed 2026-09-24).
  // SameSite=None lets the cookie travel in the frame; Partitioned (CHIPS)
  // keys it to the top-level site, so it exists only on this app's own
  // pages and inside the workspace frame, never on another site's page,
  // which is what keeps SameSite=None safe. Secure is required by both.
  // A browser without CHIPS (Safari before 18.4) ignores Partitioned and
  // still cannot hold the session in the frame; the preview in its own
  // tab works everywhere. Platform-owned, like every line of this file.
  advanced: {
    defaultCookieAttributes: {
      sameSite: 'none',
      secure: true,
      partitioned: true,
    },
  },
  plugins: [tanstackStartCookies()],
})
