// This file is automatically generated by FireVibe. Do not edit it directly.
//
// Usage: import { db } from '@/server/db' and use it ONLY in server code —
// createServerFn handlers, server route handlers, or other modules under
// src/server/. The '@tanstack/react-start/server-only' marker below makes any
// client-reachable import of this module a hard build error, so the database
// can never leak into the browser bundle. To change the database schema, edit
// src/server/schema.ts (never this file).
import '@tanstack/react-start/server-only'

import { neon } from '@neondatabase/serverless'
import { drizzle } from 'drizzle-orm/neon-http'

import * as schema from './schema'

function databaseUrl(): string {
  const url = process.env['DATABASE_URL']
  if (!url) {
    throw new Error(
      'DATABASE_URL is not set. In development it lives in the project .env file ' +
        '(written by FireVibe when the backend is enabled); in production it is a ' +
        'Worker secret injected at deploy time.',
    )
  }
  return url
}

// The Neon serverless driver speaks SQL over HTTPS — no TCP connections to
// pool, which is exactly right for Cloudflare Workers. `casing: 'snake_case'`
// maps camelCase columns in schema.ts to snake_case Postgres identifiers; the
// same setting in drizzle.config.ts keeps generated migrations in agreement.
export const db = drizzle({
  client: neon(databaseUrl()),
  schema,
  casing: 'snake_case',
})
