// This file is generated by FireVibe as the app's database schema, and it is
// the one server file that is MEANT to be edited: define every table here
// with Drizzle (schema-as-code). The workflow is always
//
//   1. edit this file
//   2. bun run db:generate   → writes SQL migrations into ./drizzle
//   3. bun run db:migrate    → applies them to the database
//
// FireVibe agent: call the migrate_database TOOL instead of steps 2-3 —
// it runs both, shows the user the SQL, and checkpoints the workspace
// (raw bun migrate skips the checkpoint and is never the right path).
//
// Never write SQL migrations by hand and never edit files under ./drizzle.
// Write column keys in camelCase — they become snake_case identifiers in
// Postgres automatically (the `casing` option set in src/server/db.ts and
// drizzle.config.ts). Query types are inferred from these definitions, so
// there is no separate type-generation step.
//
// The auth tables (user, session, account, verification) and files table are
// part of the schema — NEVER remove these lines.
export * from './auth-schema'
export * from './storage-schema'

import { pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core'

export const quoteInquiries = pgTable('quote_inquiries', {
  id: uuid().primaryKey().defaultRandom(),
  name: text().notNull(),
  email: text().notNull(),
  phone: text(),
  projectType: text().notNull(),
  message: text().notNull(),
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
})
