// This file is automatically generated by FireVibe. Do not edit it directly.
//
// requireSession is the authorization chokepoint: EVERY server function that
// touches data must include it in its middleware chain —
//
//   createServerFn().middleware([requireSession]).handler(({ context }) => {
//     // context.session.user / context.session.session are guaranteed here
//   })
//
// Anonymous calls are rejected with 401 before the handler runs. For page
// UX (redirecting signed-out visitors), gate routes in app code with a
// layout's beforeLoad instead — this module protects the DATA, routes shape
// the experience.
//
// This module is deliberately NOT server-only: middleware is referenced by
// the client-side RPC stub of any server function using it, so it must stay
// client-importable. Only the .server() callback below touches auth — the
// compiler strips it from the client bundle, and the build fails if anything
// server-only ever leaks through.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'

import { auth } from './auth'

export const requireSession = createMiddleware().server(async ({ next }) => {
  const session = await auth.api.getSession({
    headers: getRequest().headers,
  })
  if (!session) {
    throw new Response('Unauthorized', { status: 401 })
  }
  return next({ context: { session } })
})
