// This file is automatically generated by FireVibe. Do not edit it directly.
//
// The files table backing this app's object storage: every uploaded object
// gets one row (the object itself lives in the app's storage bucket, never
// in Postgres). It is part of the schema via `export * from
// './storage-schema'` in schema.ts — never remove that line and never
// redefine this table. App tables that reference uploads should point at
// `files.id` from this file.
import { bigint, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

import { user } from "./auth-schema";

export const files = pgTable("files", {
  id: uuid().primaryKey().defaultRandom(),
  // The object key in the bucket (see newFileKey in storage.ts).
  key: text().notNull().unique(),
  // Original filename, for display and download naming.
  name: text().notNull(),
  contentType: text().notNull(),
  // Byte size, recorded when the upload is confirmed server-side.
  size: bigint({ mode: "number" }),
  // Uploader; kept nullable so deleting a user keeps their files' rows.
  userId: text().references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
});
