// This file is automatically generated by FireVibe. Do not edit it directly.
//
// Object storage for this app: presigned uploads and downloads against the
// app's own bucket. The browser NEVER holds storage credentials — the flow
// is always
//
//   1. a server function (behind requireSession) calls presignUpload()
//   2. the browser PUTs the file straight to the returned URL
//   3. the server function records the row in the `files` table (schema in
//      storage-schema.ts) — record `size` there when confirming; a presigned
//      PUT cannot enforce a size limit by itself
//
// Storage is configured by FireVibe when enabled for this app; until then
// these functions throw with a clear message (import alone is always safe).
import '@tanstack/react-start/server-only'

import { AwsClient } from 'aws4fetch'

interface StorageEnv {
  accountId: string
  accessKeyId: string
  secretAccessKey: string
  bucket: string
}

function storageEnv(): StorageEnv {
  const accountId = process.env['R2_ACCOUNT_ID']
  const accessKeyId = process.env['R2_ACCESS_KEY_ID']
  const secretAccessKey = process.env['R2_SECRET_ACCESS_KEY']
  const bucket = process.env['R2_BUCKET']
  if (!accountId || !accessKeyId || !secretAccessKey || !bucket) {
    throw new Error(
      'Object storage is not configured for this app yet. FireVibe sets ' +
        'R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY and R2_BUCKET ' +
        'when storage is enabled.',
    )
  }
  return { accountId, accessKeyId, secretAccessKey, bucket }
}

let cachedClient: AwsClient | undefined

function client(env: StorageEnv): AwsClient {
  cachedClient ??= new AwsClient({
    accessKeyId: env.accessKeyId,
    secretAccessKey: env.secretAccessKey,
    service: 's3',
    region: 'auto',
  })
  return cachedClient
}

function objectUrl(env: StorageEnv, key: string, expiresInSeconds: number): string {
  const url = new URL(
    `https://${env.accountId}.r2.cloudflarestorage.com/${env.bucket}/${key}`,
  )
  url.searchParams.set('X-Amz-Expires', String(expiresInSeconds))
  return url.toString()
}

/** A collision-proof object key that keeps the original name readable. */
export function newFileKey(filename: string): string {
  const safe = filename.replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 128)
  return `${crypto.randomUUID()}/${safe}`
}

/** Presigned PUT URL the browser uploads to directly. */
export async function presignUpload(
  key: string,
  expiresInSeconds = 900,
): Promise<string> {
  const env = storageEnv()
  const signed = await client(env).sign(objectUrl(env, key, expiresInSeconds), {
    method: 'PUT',
    aws: { signQuery: true },
  })
  return signed.url
}

/** Presigned GET URL for time-limited downloads of a stored object. */
export async function presignDownload(
  key: string,
  expiresInSeconds = 900,
): Promise<string> {
  const env = storageEnv()
  const signed = await client(env).sign(objectUrl(env, key, expiresInSeconds), {
    method: 'GET',
    aws: { signQuery: true },
  })
  return signed.url
}
