// This file is automatically generated by FireVibe. Do not edit it directly.
//
// The browser-side auth client. Use it in components for every auth
// interaction — it talks to this app's own /api/auth/* endpoints on the
// current origin (no configuration needed):
//
//   import { authClient } from '@/lib/auth-client'
//
//   await authClient.signUp.email({ email, password, name })
//   await authClient.signIn.email({ email, password })
//   await authClient.signOut()
//   const { data: session } = authClient.useSession()   // React hook
import { createAuthClient } from 'better-auth/react'

export const authClient = createAuthClient()
