// This file is automatically generated by FireVibe. Do not edit it directly.
//
// Mounts Better Auth's HTTP endpoints at /api/auth/* (its default basePath):
// sign-up, sign-in, sign-out, get-session and every future auth flow all
// route through this single handler. Browser code should use
// '@/lib/auth-client' instead of calling these endpoints by hand.
import { createFileRoute } from '@tanstack/react-router'

import { auth } from '@/server/auth'

export const Route = createFileRoute('/api/auth/$')({
  server: {
    handlers: {
      ANY: ({ request }) => auth.handler(request),
    },
  },
})
