// This file is automatically generated by FireVibe. Do not edit it directly.
//
// drizzle-kit reads this config for `bun run db:generate` (schema → SQL
// migrations in ./drizzle, no database connection needed) and
// `bun run db:migrate` (applies ./drizzle to DATABASE_URL). drizzle-kit loads
// the project .env itself, so the same .env that serves `vite dev` also
// serves migrations. To change the schema, edit src/server/schema.ts.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './src/server/schema.ts',
  out: './drizzle',
  casing: 'snake_case',
  dbCredentials: {
    // The empty fallback keeps offline commands (generate) working without a
    // database; migrate fails loudly on connect when DATABASE_URL is missing.
    url: process.env['DATABASE_URL'] ?? '',
  },
})
